services:
  pico-tests:
    ports:
      - "5900:5900"
      - "6080:6080" # webvnc server: http://localhost:6080/vnc.html
      - "8000:8000" # PicoLimbo Build API
    volumes:
      - ./integration_tests_reports:/app/integration_tests_reports
      - ./full_screenshots:/app/full_screenshots
      - ./cache/.minecraft:/root/.minecraft
      - ./cache/minecraft:/app/minecraft
      - ./cache/cargo:/root/.cargo
      - ./cache/repos:/app/repos
      - ./cache/builds:/app/builds
      - ./cache/proxies:/app/cache/proxies
    build: .
    privileged: true
